// TODO check and update
const key_codes = [
  'left_arrow',
  'right_arrow',
  'caps_lock',
  'escape',
  'spacebar',
  'tab',
  'down_arrow',
  'up_arrow',
  'page_up',
  'page_down',
  'hyphen',
  'home',
  'end',
  'grave_accent_and_tilde',
  'equal_sign',
  'return_or_enter',
  'delete_or_backspace',
  'comma',
  'period',
  'delete_forward',
  'keypad_enter',
  'keypad_period',
  'keypad_plus',
  'keypad_hyphen',
  'keypad_num_lock',
  'keypad_equal_sign',
  'left_shift',
  'right_shift',
  'keypad_slash',
  'keypad_asterisk',
  '0',
  '1',
  '2',
  '3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  'keypad_0',
  'keypad_1',
  'keypad_2',
  'keypad_3',
  'keypad_4',
  'keypad_5',
  'keypad_6',
  'keypad_7',
  'keypad_8',
  'keypad_9',
  'f1',
  'f2',
  'f3',
  'f4',
  'f5',
  'f6',
  'f7',
  'f8',
  'f9',
  'open_bracket',
  'close_bracket',
  'slash',
  'backslash',
  'quote',
  'display_brightness_decrement',
  'illumination_decrement',
  'rewind',
  'play_or_pause',
  'fastforward',
  'mute',
  'display_brightness_increment',
  'volume_decrement',
  'volume_increment',
  'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h',
  'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p',
  'q', 'r', 's', 't', 'u', 'v', 'w', 'x',
  'y', 'z',
] as const;

export type KeyCodeType = (typeof key_codes)[number];
